"Name: \TY:CL_FML_MATL_MASTER_UI_SERVICE\ME:IS_STATISTICAL_MAP_RELEVANT\SE:BEGIN\EI
ENHANCEMENT 0 /SIMPLE/MAP_RELEVANT1.
*
  if /simple/prd_service_provider=>gv_mdg = 'X'.
    exit.
  endif.

ENDENHANCEMENT.
